dist: xenial
os:
  - linux

services:
  - docker

install:
  - echo "install"

before_script:
  - echo "before script"

script:
  - cd action-a
  - docker build -t actions-demo .
  - echo $DOCKER_USERNAME
  - docker tag actions-demo $DOCKER_USERNAME/actions-demo:latest
  - docker image ls

after_success:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push $DOCKER_USERNAME/actions-demo:latest
